stages:
  - test
  - deploy

sast:
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml

sync-to-github:
  stage: deploy
  only:
    - main
    - develop
  script:
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/idibau/cs2bim.git || true
    - git push github HEAD:${CI_COMMIT_BRANCH}

set-github-pages:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - |
      curl -s -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github+json" \
        https://api.github.com/repos/idibau/cs2bim/pages \
        -d '{
          "source": {
            "branch": "main",
            "path": "/_book"
          }
        }'
  only:
    - develop