################# general ###################
logging_level: INFO

########## postgis configuration ############
db:
  dbname: "cs2bim"
  user: "postgres"
  host: "host.docker.internal"
  port: 5432
  password: "?"

########## stac configuration ############
stac:
  dtm_items_url: "https://data.geo.admin.ch/api/stac/v0.9/collections/ch.swisstopo.swissalti3d/items"
  building_items_url: "https://data.geo.admin.ch/api/stac/v0.9/collections/ch.swisstopo.swissbuildings3d_3_0/items"

############# tin configuration #############
tin:
  grid_size: 0.5
  max_height_error: 0.05

############# ifc configuration #############
ifc:
  author: "FHNW"
  version: "1.0"
  application_name: "cs2bim"
  project_name: "cs2bim"
  geo_referencing: LO_GEO_REF_50
  triangulation_representation_type: TESSELLATION
  clipped_terrain:
    parcel:
      sql_path: "/workspace/sql/parcels.sql"
      entity_type: IFC_GEOGRAPHIC_ELEMENT
      attributes:
        - name: "PredefinedType"
          column: "predefined_type"
        - name: "ObjectType"
          column: "object_type"
        - name: "Name"
          column: "egris_egrid"
      properties:
        - name: "NBIdent"
          set: "CHKGK_CS"
          column: "nbident"
        - name: "Nummer"
          set: "CHKGK_CS"
          column: "nummer"
        - name: "EGRIS_EGRID"
          set: "CHKGK_CS"
          column: "egris_egrid"
      spatial_structure:
        entity_type: IFC_SITE
        attributes:
          - name: "CompositionType"
            value: "COMPLEX"
          - name: "PredefinedType"
            value: "USERDEFINED"
          - name: "ObjectType"
            value: "Liegenschaften"
          - name: "Name"
            value: "Liegenschaften"
      group_columns:
        - "group"
      color:
        r: 0.31
        g: 0.67
        b: 0.04
        a: 0.85
    land_cover:
      sql_path: "/workspace/sql/land_covers.sql"
      entity_type: IFC_GEOGRAPHIC_ELEMENT
      attributes:
        - name: "PredefinedType"
          column: "predefined_type"
        - name: "ObjectType"
          column: "art"
        - name: "Name"
          column: "art"
      properties: [ ]
      spatial_structure:
        entity_type: IFC_SITE
        attributes:
          - name: "CompositionType"
            value: "COMPLEX"
          - name: "PredefinedType"
            value: "USERDEFINED"
          - name: "ObjectType"
            value: "Bodenbedeckung"
          - name: "Name"
            value: "Bodenbedeckung"
      group_columns:
        - "group"
      color:
        r: 0.52
        g: 0.42
        b: 0.04
        a: 0.85
    land_covers_buildings:
      sql_path: "/workspace/sql/land_covers_buildings.sql"
      entity_type: IFC_GEOGRAPHIC_ELEMENT
      attributes:
        - name: "PredefinedType"
          column: "predefined_type"
        - name: "ObjectType"
          column: "art"
        - name: "Name"
          column: "gwr_egid"
      properties:
        - name: "GWR-EGID"
          set: "CHKGK_CS"
          column: "gwr_egid"
      spatial_structure:
        entity_type: IFC_SITE
        attributes:
          - name: "CompositionType"
            value: "COMPLEX"
          - name: "PredefinedType"
            value: "USERDEFINED"
          - name: "ObjectType"
            value: "Geb채ude"
          - name: "Name"
            value: "Geb채udegrundfl채chen"
      group_columns:
        - "group"
      color:
        r: 1.00
        g: 0.00
        b: 0.00
        a: 0.85
  building:
    all:
      sql_path: "/workspace/sql/egid.sql"
      egid_xpath: ".//gen:intAttribute[@name='EGID']/gen:value"
      spatial_structure:
        entity_type: IFC_SITE
        attributes:
          - name: "Name"
            value: "Geb채ude"
      attributes:
        - name: "Name"
          xpath: ".//gen:intAttribute[@name='EGID']/gen:value"
      properties:
        - name: "Erstellung Jahr"
          set: "Erstellung"
          xpath: ".//gen:intAttribute[@name='ERSTELLUNG_JAHR']/gen:value"
        - name: "Erstellung Monat"
          set: "Erstellung"
          xpath: ".//gen:intAttribute[@name='ERSTELLUNG_MONAT']/gen:value"
      building_parts:
        - xpath: ".//bldg:lod2Solid/gml:Solid[@srsName='EPSG:2056' and @srsDimension='3']/gml:exterior/gml:CompositeSurface/gml:surfaceMember/gml:Polygon/gml:exterior/gml:LinearRing/gml:posList"
          entity_type: IFC_SPACE
          attributes: [ ]
          properties: [ ]
          color:
            r: 1.00
            g: 1.00
            b: 1.00
            a: 0.8
        - xpath: ".//bldg:boundedBy/bldg:WallSurface/bldg:lod2MultiSurface/gml:MultiSurface/gml:surfaceMember/gml:Polygon/gml:exterior/gml:LinearRing/gml:posList"
          entity_type: IFC_WALL
          attributes: [ ]
          properties:
            - name: "Herkunft Monat"
              set: "Herkunft"
              xpath: ".//bldg:boundedBy/bldg:WallSurface/gen:intAttribute[@name='HERKUNFT_MONAT']/gen:value"
            - name: "Herkunft Jahr"
              set: "Herkunft"
              xpath: ".//bldg:boundedBy/bldg:WallSurface/gen:intAttribute[@name='HERKUNFT_JAHR']/gen:value"
            - name: "Original Herkunft"
              set: "Herkunft"
              xpath: ".//bldg:boundedBy/bldg:WallSurface/gen:stringAttribute[@name='HERKUNFT']/gen:value"
          color:
            r: 1.00
            g: 1.00
            b: 1.00
            a: 0.00
        - xpath: ".//bldg:boundedBy/bldg:RoofSurface/bldg:lod2MultiSurface/gml:MultiSurface/gml:surfaceMember/gml:Polygon/gml:exterior/gml:LinearRing/gml:posList"
          entity_type: IFC_ROOF
          attributes: [ ]
          properties: [ ]
          color:
            r: 1.00
            g: 0.8
            b: 0.8
            a: 0.00
        - xpath: ".//bldg:boundedBy/bldg:GroundSurface/bldg:lod2MultiSurface/gml:MultiSurface/gml:surfaceMember/gml:Polygon/gml:exterior/gml:LinearRing/gml:posList"
          entity_type: IFC_SLAB
          attributes: [ ]
          properties: [ ]
          color:
            r: 0.8
            g: 0.8
            b: 1.00
            a: 0.00
  groups:
    Amtliche Vermessung.Gebaeude:
      entity_type: IFC_BUILDING_SYSTEM
      attributes:
        - name: "PredefinedType"
          value: "USERDEFINED"
        - name: "ObjectType"
          value: "Gebaeude"
