################# general ###################
logging_level: INFO

########### redis configuration #############
redis:
  host: "redis"
  port: 6379
  db:
    celery_broker: 0
    celery_backend: 1
    file_cache: 2

########## postgis configuration ############
db:
  dbname: "cs2bim"
  user: "postgres"
  host: "host.docker.internal"
  port: 5432
  password: "?"

########## stac configuration ############
stac:
  dtm_items_url: "https://data.geo.admin.ch/api/stac/v0.9/collections/ch.swisstopo.swissalti3d/items"
  building_items_url: "https://data.geo.admin.ch/api/stac/v0.9/collections/ch.swisstopo.swissbuildings3d_3_0/items"

############# tin configuration #############
tin:
  grid_size: 0.5
  max_height_error: 0.05

############# ifc configuration #############
ifc:
  author: "FHNW"
  version: "1.0"
  application_name: "cs2bim"
  project_name: "cs2bim"
  geo_referencing: LO_GEO_REF_50
  feature_types:
    projections:
      - name: "parcel"
        sql_path: "/workspace/sql/parcels.sql"
        entity_mapping:
          entity_type: IFC_GEOGRAPHIC_ELEMENT
        spatial_structure_mapping:
          entity_type: IFC_SITE
    buildings:
      - name: "all"
        sql_path: "/workspace/sql/egid.sql"
        egid_xpath: ".//gen:intAttribute[@name='EGID']/gen:value"
        entity_mapping:
          entity_type: IFC_BUILDING
          building_parts:
            - entity_type: IFC_BUILDING_ELEMENT_PROXY
              geometry_mapping:
                xpath: ".//bldg:lod2Solid/gml:Solid[@srsName='EPSG:2056' and @srsDimension='3']"
                type: SOLID
        spatial_structure_mapping:
          entity_type: IFC_SITE
