################# general ###################
logging_level: DEBUG

########## postgis configuration ############
db:
  dbname: "cs2bim"
  user: "postgres"
  host: "host.docker.internal"
  port: 5432
  password: "postgres"
  schema: "cs2bim"

######### swiss topo configuration ##########
swisstopo:
  stac_api: "https://data.geo.admin.ch/api/stac/v0.9/collections/ch.swisstopo.swissalti3d/items"

############# tin configuration #############
tin:
  grid_size: 0.5
  max_height_error: 0.05

############# ifc configuration #############
ifc:
  author: "FHNW"
  version: "1.0"
  application_name: "cs2bim"
  project_name: "cs2bim"
  geo_referencing: LO_GEO_REF_30
  triangulation_representation_type: TESSELLATION
  feature_classes:
    parcel:
      sql: "sql/parcels.sql"
      element_name_column: "egris_egrid"
      properties:
        - name: "NBIdent"
          column: "nbident"
          set: "CHKGK_CS" 
        - name: "Nummer"
          column: "nummer"
          set: "CHKGK_CS" 
        - name: "EGRIS_EGRID"
          column: "egris_egrid"
          set: "CHKGK_CS" 
      entity_type: IFC_GEOGRAPHIC_ELEMENT
      spatial_structure:
        entity_type: IFC_SITE 
        name: ""
      group_columns: 
        - "group"
      color_definition:
        r: 0.31
        g: 0.67
        b: 0.04
        a: 0.85
    land_cover:
      sql: "sql/land_covers_contains.sql"
      element_name_column:
      properties: []
      entity_type: IFC_GEOGRAPHIC_ELEMENT
      spatial_structure:
        entity_type: IFC_SITE 
        name: ""
      group_columns: 
        - "group"
      color_definition:  
        r: 0.52
        g: 0.42
        b: 0.04
        a: 0.85
  groups:
    Amtliche Vermessung.Feature-Klassen.Bodenbedeckung (Gebaeude):
      entity_type: IFC_DISTRIBUTION_SYSTEM
      object_type: ""
      predefined_type: "NOTDEFINED"