version: "3.7"

services:

  redis:
    container_name: redis
    image: redis:7
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis_data:/data

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace/src
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - backend
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./config.yml:/workspace/config.yml
      - ./sql:/workspace/sql
      - ifc_storage:/workspace/ifc_storage

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace/src
    command: celery -A worker.app.app worker --concurrency=2
    depends_on:
      - redis
    networks:
      - backend
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./config.yml:/workspace/config.yml
      - ./sql:/workspace/sql
      - ifc_storage:/workspace/ifc_storage

networks:
  backend:
    driver: bridge

volumes:
  redis_data:
  ifc_storage: