from enum import Enum


class GroupEntity(Enum):
    """Supported ifc entity types for groups"""

    IFC_DISTRIBUTION_SYSTEM = "IFC_DISTRIBUTION_SYSTEM"
    IFC_DISTRIBUTION_CIRCUIT = "IFC_DISTRIBUTION_CIRCUIT"
    IFC_BUILDING_BUILT_SYSTEM = "IFC_BUILDING_BUILT_SYSTEM"
    IFC_STRUCTURAL_ANALYSIS_MODEL = "IFC_STRUCTURAL_ANALYSIS_MODEL"
    IFC_ZONE = "IFC_ZONE"
