from enum import Enum


class GroupEntityType(Enum):
    """Supported ifc entity types for groups"""

    IFC_DISTRIBUTION_SYSTEM = "IFC_DISTRIBUTION_SYSTEM"
    IFC_DISTRIBUTION_CIRCUIT = "IFC_DISTRIBUTION_CIRCUIT"
    IFC_BUILDING_SYSTEM = "IFC_BUILDING_SYSTEM"
    # IFC_BUILT_SYSTEM = "IFC_BUILT_SYSTEM"  This entity type is only supported in 4.3
    IFC_STRUCTURAL_ANALYSIS_MODEL = "IFC_STRUCTURAL_ANALYSIS_MODEL"
    IFC_ZONE = "IFC_ZONE"
